[REM] add new submodules and remove deprecated ones. T#53841
Vauxoo/confetex pull request #11
Opened 2022-05-17 03:13 UTC by agarzaarvizu

### This MR refers to the task[#53841](https://www.vauxoo.com/web#id=53841&action=1928&model=project.task&view_type=form&cids=1&menu_id=1490)

- Remove deprecated submodules
- Add new dependencies

2022-05-17 03:14 UTC, agarzaarvizu commented
@desdelinux @hugho-ad Done.

2022-05-17 16:03 UTC, hugho-ad commented
el submodulo de reporting-engine por que lo necesitamos?

2022-05-17 16:51 UTC, desdelinux commented
Porque se usa en el siguiente módulo: https://git.vauxoo.com/vauxoo/confetex/-/tree/15.0/hyd_stock_card

2022-05-18 02:21 UTC, luisg123v requested changes
Missing `sh-tools`

2022-05-18 02:36 UTC, agarzaarvizu commented
@luisg123v Done

2022-05-18 03:07 UTC, luisg123v approved these changes
LGTM :+1:

2022-05-18 03:07 UTC, merged